# SPDX-FileCopyrightText: 2021 Anthony Potdevin
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Lightning Node Management
  name: ThunderHub
  version: 0.12.31
  tagline: Take full control of your Lightning node
  description: 'ThunderHub allows you to take full control of your Lightning node
    with a slick and awesome UI. Explore all the options that ThunderHub has to offer,
    from sending and receiving Lightning payments, to checking your node''s health
    statistics, and even more advanced options like channel rebalancing and multi-path
    lightning payments.


    Managing and monitoring your node has never been easier with transaction reports,
    graphs and a huge assortment of different features all bundled inside of this
    great tool.'
  developer: Anthony Potdevin
  website: https://apotdevin.com
  dependencies:
  - lnd
  repo: https://github.com/apotdevin/thunderhub
  support: https://t.me/thunderhub
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
containers:
- image: apotdevin/thunderhub:v0.13.6@sha256:b439b00f23376f932acd9c13e5037dd5870740dd66e3ebb7065a9d62a4fc370d
  #user: 1000:1000
  environment:
    NO_VERSION_CHECK: 'true'
    LOG_LEVEL: debug
    ACCOUNT_CONFIG_PATH: /data/thubConfig.yaml
    YML_ENV_1: $LND_IP:$LND_GRPC_PORT
    MASTER_PASSWORD_OVERRIDE: $APP_SEED
    TOR_PROXY_SERVER: socks://$TOR_PROXY_IP:$TOR_PROXY_PORT
  name: web
  port: 3000
  data:
  - data:/data
  permissions:
  - lnd
