# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Development
  name: code-server
  version: 4.0.1
  tagline: Run VS Code on your Citadel
  description: >-
    This app doesn't  have a description yet.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED

containers:
- name: server
  image: codercom/code-server:4.0.1@sha256:e73d681aae4fdc76197bac643289378823ee53fc029c511ec55313db20d92598
  user: 1000:1000
  environment:
    PASSWORD: $APP_SEED
  data:
  - data:/home/coder
