# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2

metadata:
  category: Development
  name: code-server
  version: 4.0.2
  tagline: Run VS Code on your Citadel
  description: This app doesn't  have a description yet.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: server
    image: codercom/code-server:4.0.2@sha256:4de6369f5865c7db250fa25e3e2306ed5a3f0bad922c9392d52c0dd1dd7e4fd6
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    data:
      - data:/home/coder
