# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: Development
  name: code-server
  version: 4.1.0
  tagline: Run VS Code on your Citadel
  description: This app doesn't  have a description yet.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: server
    image: codercom/code-server:4.1.0@sha256:ed9c83c6f2a84b7d6c72a536d210e9e61f7aa5185a0ce4d6e9ae37aa1ff5932f
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    data:
      - data:/home/coder
