# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Lightning Node Management
  name: Lightning Shell
  version: 1.1.1
  tagline: Web shell with a selection of LN node management utilities
  description: >-
    This app allows you to access a lot of terminal apps directly on the web.

    The default username for this app is (currently) "umbrel".
  developer: Ioan Bizău
  website: Ioan Bizău
  dependencies:
    - lnd
  repo: https://ibz.github.io/lightning-shell/
  support: https://github.com/ibz/lightning-shell/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED

containers:
  - name: web
    image: ghcr.io/runcitadel/lightning-shell:main@sha256:339f14bbc54828a2b0238e11a848275e2b4beb8ebfae53472dc1307cd62d2a7d
    restart: on-failure
    stop_grace_period: 1m
    port: 7681
    data:
    - data:/data
    environment:
        APP_PASSWORD: "${APP_SEED}"
