# SPDX-FileCopyrightText: 2021 Aaron Dewes <aaron.dewes@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: Explorers
  name: Bitfeed
  version: 2.2.0
  tagline: A live visualization of your node's mempool
  description: A self-hosted version of Bitfeed - the open source mempool & block
    visualizer available at https://bits.monospace.live. Watch as new
    transactions drop into your node's mempool, before being packaged into newly
    mined blocks. Monitor Bitcoin network activity, explore the composition of
    the latest block, or simply enjoy a soothing Bitcoin screensaver.
  developer: Mononaut
  website: https://monospace.live
  dependencies:
    - bitcoind
  repo: https://github.com/bitfeed-project/bitfeed
  support: https://github.com/bitfeed-project/bitfeed/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  updateContainer:
    - main
    - api
containers:
  - name: main
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.2.0@sha256:050c4e7c7744a856fbd49758db046c4dfead40d39a0719f35b3918e9f778b074
    restart: on-failure
    stop_grace_period: 1m
    port: 80
    depends_on:
      - api
    environment:
      TARGET: citadel
      BACKEND_HOST: $APP_BITFEED_API_IP
      BACKEND_PORT: "3000"
  - name: api
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.2.0@sha256:b04d9ef4f2c56bd25cd1cb6b33261a8716d6710d71c7e3c0388d12f2cc236e11
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "3000"
      BITCOIN_HOST: $BITCOIN_IP
      BITCOIN_ZMQ_RAWTX_PORT: $BITCOIN_ZMQ_RAWTX_PORT
      BITCOIN_ZMQ_RAWBLOCK_PORT: $BITCOIN_ZMQ_RAWBLOCK_PORT
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
    data:
      - data:/app/data
    permissions:
      - bitcoind
