# SPDX-FileCopyrightText: 2021 Kilian Botrel
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: Lightning Node Management
  name: LNDg
  version: 1.0.3
  tagline: Lite GUI web interface to analyze LND data and manage your node with
    automation.
  description: LNDg is your command center for running a profitable and efficient
    routing node. From quickly viewing your node's health, automated
    rebalancing, selecting new potential peers and much more.
  developer: cryptosharks131
  website: https://github.com/cryptosharks131
  dependencies:
    - lnd
  repo: https://github.com/cryptosharks131/lndg
  support: https://t.me/+-RxoZdi7snk2ZGYx
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultPassword: $APP_SEED
containers:
  - name: web
    image: ghcr.io/cryptosharks131/lndg:v1.0.3@sha256:a179456526cb9f8b7b804129d47f7b72fc6bae0ecbf1df999382b5513c188915
    restart: on-failure
    stop_grace_period: 1m
    lnd_mount_dir: /root/.lnd
    data:
      - data:/lndg/data
    command:
      - sh
      - -c
      - python initialize.py -net '${BITCOIN_NETWORK}' -server
        '${LND_IP}:${LND_GRPC_PORT}' -pw '${APP_SEED}' -d && supervisord &&
        python manage.py runserver 0.0.0.0:${APP_LNDG_WEB_PORT}
    permissions:
      - lnd
